POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
        "title": "Sample Blog 5",
        "author": "Eva Williams",
        "url": "http://sampleblog5.com",
        "likes": 120
    }